### ISSUE TITLE
Config assumes use of fullnode.dappnode

### ISSUE THREAD

**Issue by AJolly** [MysticRyuujin/dappnode-dshackle#1]
The default config assumes DappNode is using fullnode.dappnode for its local node URL.
This isnt always correct - for example if you are using the Erigon package rather than Geth.

ps. Thanks for pushing out the package!

**Comment by MysticRyuujin** [comment]
That's why it's configurable via the yaml file and there are instructions in the README 🤷‍♂️

If you have a better default let me know.

**Comment by AJolly** [comment]
I've got the config file modified for me, was more wondering about exposing it in the advanced config page to make it easier for most people.

Filed a bug with the DappNode team, I'm not sure they realize you can't pick Erigon as an option for the full node variable (they seem to be maintaining the Erigon package)  

ps Whats the easiest way you know to modify the config file?  The File Manager on the package config file never seems to work for me.

**Comment by MysticRyuujin** [comment]
I dunno, I've never had any issues with the file manager. I download it and upload it from there, then restart service.
